Repository NVIDIA/k8s-dra-driver-gpu, pull requests merged in 2025-08, with the labels that each got.

#452 Add a MultiNamespaceDaemonsetManager for ComputeDomains
  cmd/compute-domain-controller/cleanup.go
  cmd/compute-domain-controller/computedomain.go
  cmd/compute-domain-controller/controller.go
  cmd/compute-domain-controller/daemonset.go
  cmd/compute-domain-controller/main.go
  cmd/compute-domain-controller/mnsdaemonset.go
  cmd/compute-domain-controller/node.go
  cmd/compute-domain-controller/resourceclaimtemplate.go
  cmd/compute-domain-daemon/computedomain.go
  cmd/compute-domain-kubelet-plugin/computedomain.go
  deployments/helm/nvidia-dra-driver-gpu/templates/_helpers.tpl
  deployments/helm/nvidia-dra-driver-gpu/templates/clusterrole.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/clusterrolebinding.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/compute-domain-daemon-rbac.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/controller.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/rbac.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/serviceaccount.yaml
  deployments/helm/nvidia-dra-driver-gpu/values.yaml
Labels: security

#470 Use 'distroless' prod image
  deployments/container/Dockerfile
  deployments/container/Makefile
  deployments/devel/Makefile
  versions.mk
Labels: build artifacts

#481 Update the version used during CI to match ${VERSION}-${SHORT_GIT_SHA}
  .github/workflows/variables.yaml
  versions.mk
Labels: bug

#485 Add kubeVersion to helm chart
  deployments/helm/nvidia-dra-driver-gpu/Chart.yaml
Labels: release

#462 Add feature gates for TimeSlicing and MPS settings
  api/nvidia.com/resource/v1beta1/gpuconfig.go
  api/nvidia.com/resource/v1beta1/migconfig.go
  api/nvidia.com/resource/v1beta1/validate.go
  cmd/gpu-kubelet-plugin/device_state.go
  cmd/webhook/main_test.go
  pkg/featuregates/featuregates.go
  pkg/featuregates/featuregates_test.go
Labels: feature

#453 Add liveness probe to kubelet-plugin
  cmd/compute-domain-kubelet-plugin/driver.go
  cmd/compute-domain-kubelet-plugin/health.go
  cmd/compute-domain-kubelet-plugin/main.go
  cmd/gpu-kubelet-plugin/driver.go
  cmd/gpu-kubelet-plugin/health.go
  cmd/gpu-kubelet-plugin/main.go
  deployments/helm/nvidia-dra-driver-gpu/templates/kubeletplugin.yaml
  deployments/helm/nvidia-dra-driver-gpu/values.yaml
  go.mod
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/modules.txt
Labels: feature

#492 Fix bash cross-compilation amd64->arm64
  deployments/container/Dockerfile
Labels: bug

#509 Update vendoring to kubernetes v1.34.0
  go.mod
  go.sum
  vendor/k8s.io/api/certificates/v1alpha1/types.go
  vendor/k8s.io/api/certificates/v1alpha1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/component-base/version/.gitattributes
  vendor/k8s.io/mount-utils/README.md
  vendor/modules.txt
Labels: dependencies
