Repository NVIDIA/k8s-dra-driver-gpu, pull requests merged in 2025-10, with the labels that each got.

#632 Use single informer for all ComputeDomain daemonset pods
  cmd/compute-domain-controller/daemonset.go
  cmd/compute-domain-controller/daemonsetpods.go
Labels: robustness

#630 CD plugin: log detail around fabric cliqueID readout
  cmd/compute-domain-kubelet-plugin/device_state.go
  cmd/compute-domain-kubelet-plugin/nvlib.go
Labels: robustness, debuggability

#637 tests: fixes, improved cleanup & stability, better debuggability
  .gitignore
  tests/bats/Makefile
  tests/bats/cleanup-from-previous-run.sh
  tests/bats/helpers.sh
  tests/bats/setup_suite.bash
  tests/bats/tests.bats
Labels: ci/testing

#624 Remove GPU index for CDI spec generation / attribute advertisement
  cmd/gpu-kubelet-plugin/allocatable.go
  cmd/gpu-kubelet-plugin/cdi.go
  cmd/gpu-kubelet-plugin/deviceinfo.go
  cmd/gpu-kubelet-plugin/nvlib.go
  cmd/gpu-kubelet-plugin/prepared.go
Labels: usability

#644 Logging improvements for debuggability (CD daemon, plugin)
  cmd/compute-domain-daemon/main.go
  cmd/compute-domain-kubelet-plugin/driver.go
Labels: debuggability

#651 CD daemon: coordinate CD updates on shutdown via mutation cache
  cmd/compute-domain-daemon/computedomain.go
  cmd/compute-domain-daemon/podmanager.go
  tests/bats/tests.bats
Labels: robustness, usability
