Repository NVIDIA/k8s-dra-driver-gpu, pull requests merged in 2025-09, with the labels that each got.

#516 Update the version used during CI to match ${VERSION}-${SHORT_GIT_SHA}
  .github/workflows/variables.yaml
  versions.mk
Labels: ci/testing

#515 Add GHA workflow to push Helm chart to GHCR
  .github/workflows/chart.yaml
  .github/workflows/ci.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/_helpers.tpl
Labels: build artifacts

#510 fix: compute domain startup probe on ipv6 with driver 580+
  templates/compute-domain-daemon-config.tmpl.cfg
Labels: bug

#511 fix: compute domain startup probe on ipv6 with driver 580+
  templates/compute-domain-daemon-config.tmpl.cfg
Labels: bug

#519 Delay cleanup of the ComputeDomain config dir on daemon cleanup
  cmd/compute-domain-kubelet-plugin/computedomain.go
Labels: bug, backport-25.3

#520 Add logic in workqueue to dedup tasks submitted with same key
  pkg/workqueue/workqueue.go
Labels: bug, backport-25.3

#521 Use the same workqueue key for Prepare/UnprepareResources on same claim
  cmd/compute-domain-kubelet-plugin/driver.go
Labels: bug, backport-25.3

#488 Update kubelet plugin signal handling on shutdown
  cmd/compute-domain-kubelet-plugin/main.go
  cmd/gpu-kubelet-plugin/main.go
Labels: cleanup

#534 Conditionally set the apiVersion of all device classes we install
  deployments/helm/nvidia-dra-driver-gpu/templates/_helpers.tpl
  deployments/helm/nvidia-dra-driver-gpu/templates/deviceclass-compute-domain-daemon.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/deviceclass-compute-domain-default-channel.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/deviceclass-gpu.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/deviceclass-mig.yaml
  deployments/helm/nvidia-dra-driver-gpu/templates/validation.yaml
Labels: bug, backport-25.3

#540 Patch IMEX config file with Pod IP where IMEX daemon runs
  cmd/compute-domain-daemon/main.go
  cmd/compute-domain-kubelet-plugin/computedomain.go
  templates/compute-domain-daemon-config.tmpl.cfg
Labels: bug, backport-25.3

#538 [backport] Patch IMEX config file with Pod IP where IMEX daemon runs
  cmd/compute-domain-daemon/main.go
  cmd/compute-domain-kubelet-plugin/computedomain.go
  templates/compute-domain-daemon-config.tmpl.cfg
Labels: bug

#541 Add readiness probe and update startup/liveness probes on CD daemon
  templates/compute-domain-daemon.tmpl.yaml
Labels: robustness, backport-25.3

#542 [backport] Add readiness probe and update startup/liveness probes on CD daemon
  templates/compute-domain-daemon.tmpl.yaml
Labels: robustness

#556 [backport] Use just the binary name for the IMEX bins not their full path to exec
  cmd/compute-domain-daemon/main.go
Labels: bug

#554 [no-relnote] Cleanup makefile to build container image
  deployments/container/Makefile
  deployments/container/multi-arch.mk
  deployments/container/native-only.mk
Labels: ci/testing, build artifacts

#580 [backport] Ignore unknown fields when decoding checkpoint JSON
  api/nvidia.com/resource/v1beta1/api.go
Labels: bug

#579 Ignore unknown fields when decoding opaque config JSON documents
  api/nvidia.com/resource/v1beta1/api.go
Labels: bug, backport-25.3

#572 Add bats-based test suite (focus on ComputeDomains)
  Makefile
  tests/bats/Dockerfile
  tests/bats/Makefile
  tests/bats/README.md
  tests/bats/clean-state-dirs-all-nodes.sh
  tests/bats/cleanup-from-previous-run.sh
  tests/bats/tests.bats
  versions.mk
Labels: ci/testing

#594 [backport] helm: DeviceClass apiVersion: prefer v1beta2 over v1beta1
  deployments/helm/nvidia-dra-driver-gpu/templates/_helpers.tpl
Labels: bug

#604 Bump version to v25.3.3
  deployments/helm/nvidia-dra-driver-gpu/Chart.yaml
  versions.mk
Labels: build artifacts

#602 bats-tests: skip test dynamically based on chart version
  tests/bats/tests.bats
Labels: ci/testing
